apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-pubsub
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: host
      value: "amqp://localhost:8395"
    - name: durable
      value: "false"
    - name: deletedWhenUnused
      value: "false"
    - name: autoAck
      value: "true"
    - name: deliveryMode
      value: "0"
    - name: requeueInFailure
      value: "false"
    - name: prefetchCount
      value: "0"
    - name: reconnectWait
      value: "0"
    - name: concurrencyMode
      value: parallel